[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18" # Ou la version de Node.js que vous utilisez

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
